name: Laravel

on: [push]

jobs:
  test_task:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: composer install
      run: composer install 

  master_task:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f
    - name: Execute migration
      run: heroku run php artisan migrate -a ${{ secrets.HEROKU_APP_NAME }}